### ISSUE TITLE
Show list of available pools

### ISSUE THREAD

**Issue by rraallvv** [Albermonte/NIM-Pools-Hub-Miner#1]
https://miner.nimiq.com/mining-pools-mainnet.json

**Comment by rraallvv** [comment]
And maybe the hashing distribution for each pool in the list

https://api.nimiq.watch/statistics/miners/24
https://nimiq.watch/script.js

**Comment by Albermonte** [comment]
Already working on it, it will be available on the next release

![image](https://user-images.githubusercontent.com/14013679/86477482-d100b180-bd48-11ea-951e-5ca3ed6d6fba.png)

**Comment by rraallvv** [comment]
Oh wow! That's phenomenal.
