### ISSUE TITLE
Enable automatic builds and packing on Travis and release uploads to GitHub

### ISSUE THREAD

**Issue by rraallvv** [Albermonte/NIM-Pools-Hub-Miner#2]
I was able to build the app for macOS, pretty cool!

Using Travis all tree platforms (macOS, Linux, and Windows) could have their release build packed and uploaded to GitHub automatically each time a new release is pushed to the repository.

Keep up the good work.

**Comment by Albermonte** [comment]
Have you tested the nimiq_node files are working while using Travis? I was trying with appveyor

**Comment by rraallvv** [comment]
I'm not familiar with AppVeyor, but I can give it a try. To be honest I haven't tried Travis with Electron apps either, but it should be straight forward. I'll check if I can make Travis build packages for all three platforms, and then will play a bit with AppVeyor to see which one is easier for making the whole process, including uploading the built packages to GitHub.

**Comment by rraallvv** [comment]
I was able enable all platform builds on Travis with this file

https://github.com/rraallvv/nim-pools-hub-miner/blob/master/.travis.yml

I disabled the `postinstall` script from `package.json` because it would need to be platform dependent and it's better to call those from the script in `travis.yml`

Here is how to generate the token on GitHub for using with Travis 
http://blog.code4hire.com/2016/06/adding-github-token-to-travis-ci-configuration/

An alternative to generating the token manually is to run `travis setup releases` as described here
https://docs.travis-ci.com/user/deployment/releases/#authenticating-with-an-oauth-token

I had to disable the snap package build because I couldn't find a way to disable uploading the package to the store and it was giving me an error related to a missing token to access the store api

These are all the packages generated
https://github.com/rraallvv/nim-pools-hub-miner/releases/tag/travis

And the logs
https://travis-ci.org/github/rraallvv/nim-pools-hub-miner/builds/704868671
