### ISSUE TITLE
The UI shows no error but ther pool not showing shares

### ISSUE THREAD

**Issue by palinko91** [Albermonte/NIM-Pools-Hub-Miner#27]
Hello I really like this miner and I don't want to change to anything, but I have a problem with it. I start the UI with icemining pool, and after few hours I can see the pool not recieving shares, the UI shows everything is alright and my mining speed is same KH/s. After I stop and restart the mining in few mins later I can see shares coming to the pool. Right now I missed 4 hour of mining cause of this cause I haven't recognised the pool stopped to recieve shares and when I sleep I can't babysit the whole process. Did with me 3 times already so its not a one time bug. Using latest windows 10, and AMD Ryzen processor.

**Comment by palinko91** [comment]
<img width="1906" alt="Névtelen" src="https://user-images.githubusercontent.com/5522266/122464650-5eb7ca00-cfb7-11eb-9cdb-6011c74c6e26.png">

I made a pic of the problem, the miner shows everything alright but actually its not mining for 3 hours :((((

**Comment by Albermonte** [comment]
Is this happening only with icemining?

The miner has an auto reconnect feature, if the pool gets disconnected it will try to reconnect every 5 to 30 seconds

Icemining had some pronblems a couple of days ago where their servers went down, that could have been the problem

**Comment by palinko91** [comment]
Unfortunatelly this is my first pool and I haven't tried other pool yet. Which one is the one is good for a single miner?

5-30 sec reconnecting attempt is interesting, because usually when I realise the problem and restart with hand (Stop Mining - Start Mining) it's reconnecting pretty fast.

Okay I'll test a couple of more days so we can see maybe the pool's end had the problem. I did the screenshot when I posted the picture, and at june 17-18 I can see 100% availablity. https://status.icemining.ca/

**Comment by Albermonte** [comment]
You can try with [acemining](https://acemining.co/#/dashboard), they have pretty decent hashrate if you are mining for at least an hour and the payouts are only 1 NIM and fees are 0.5%, compared to icemining with 75 NIM minimun and 1.25% fee
