### ISSUE TITLE
Hub miner run but nothing appear on screen

### ISSUE THREAD

**Issue by yougs** [Albermonte/NIM-Pools-Hub-Miner#36]
i installed the last NIM pools hub miner but when i run program nothing appear en screen.

Installed on windows 10 or server 2016-2019

Any idea ?

**Comment by Albermonte** [comment]
Try opening it through the terminal and watch for any error, didn't test it on windows server, it's meant for desktops

**Comment by kvcmoneyshot** [comment]
I am having the same  issue, will show up in the task bar but nothing opens. Windows desktop

**Comment by Albermonte** [comment]
@kvcmoneyshot open the app using the command line and share here the logs please

**Comment by kvcmoneyshot** [comment]
![image](https://user-images.githubusercontent.com/95157910/143784762-6e2ff1ee-2a2a-4f5e-a28d-196fdd3c892d.png)

**Comment by Parker2k** [comment]
Thought i'd add some info here from my windows 
PC:
Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Nvidia RTX2060
16.0 GB
Windows 10 Pro
Version: 20H

![Screenshot 2021-11-29 133052](https://user-images.githubusercontent.com/7153471/143799499-e239205e-165a-4b8e-bbb4-8663f53cff7d.png)

Both running with and without Administrator

Edit: added GPU

**Comment by Albermonte** [comment]
@kvcmoneyshot you need to launch it using `& '.\NIM Pools Hub Miner.exe'`

**Comment by Albermonte** [comment]
@Parker2k maybe the RTX2060 is not supported, can you try running [NQ-Miner](https://github.com/tomkha/nq-miner) and see if it works?

**Comment by yougs** [comment]
Hi everyone issue resolved by using older version and autoupdate process install. Use portable install instead of exe installer.
Work on Windows Server and workstation.

**Comment by yougs** [comment]
Install on user appdata and no in programfiles folder.

**Comment by FSOL06** [comment]
same bug, same solution : install 0.1.7 + autoupgrade.

**Comment by Albermonte** [comment]
Read this:
https://github.com/Albermonte/NIM-Pools-Hub-Miner/issues/48#issuecomment-1290171535

**Comment by Albermonte** [comment]
Fixed with [latest release](https://github.com/Albermonte/nim-pools-hub-miner/releases/latest)
