### ISSUE TITLE
Hub miner run but nothing appear on screen

### ISSUE THREAD

**Issue by afshinraad** [Albermonte/NIM-Pools-Hub-Miner#48]
I have the same problem. The previous versions of the software ran well, but the new versions do not run at all

![image](https://user-images.githubusercontent.com/53816246/159679444-b5ef9bdf-6bb6-49dd-8bbe-779793b221a0.png)

**Comment by 1kton-neto** [comment]
I have the same problem

**Comment by DanielLaw85** [comment]
Im having same issue/problem. Only run in taskbar and unable to set anything.

Setup under  desktop, haven't try on laptop due to no personal laptop

**Comment by Albermonte** [comment]
I'll work on a fix, meanwhile open PowerShell and enter this command:
`$env:UV_THREADPOOL_SIZE=128`

**Comment by DanielLaw85** [comment]
> I'll work on a fix, meanwhile open PowerShell and enter this command: `$env:UV_THREADPOOL_SIZE=128`

I test with old version it seems running, also I have input command threadpool that you inform.
But I still have a litttle trouble, harvest 24 hour already but seems nothing to get harvest even have harshrate.
*Note- my setup is win10 that mention having issue, but my friend using win11 able to harvest even with my wallet

Hope this note may assist you to troubleshoot further.

**Comment by Albermonte** [comment]
Fixed with [latest release](https://github.com/Albermonte/nim-pools-hub-miner/releases/latest)
